---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-secret
  namespace: backend-team
spec:
  encryptedData:
    DATABASE_URL: AgAn6utPrC1cNfsnK2UtroZ4cF/tsEFIuW5dx6emJ2AF1xiMCZh5bV2+D5rjPTrlW2qXg9xQ0Zhpa8M33aIXCrahxTu0BrnhqT7fes0l+9HTDaCwOUkQZzfZWnHwEp+MMLTbgC5IYZZIgw1cewvR4eH+09Bb0IKa8ImO3vRgmliXiafJjnBsHC6XHE1cwUUKZrufFreKcA3m0Jvz04++Nl5MNay96MV27/XulRJGLHhQwwoyPYbtPbkmrIVREjU+G+ZbCXQfrIlRqaNBru94kwRzlZcQ0v6IwKp0qRRBnckKhFYh0p41JQEuEpyP8fuJ/likExvK2tNmhyBODD1Lp7kXAVfzAn8jRNVaycD5SgADT/ESZfQl1HafUmxyVm24gjD1FAn7lE4ngczAPiQU2BnSxys5st3dN+Bc0EMFjDRsc/s1Vlo0CvzJ208ShCVWN84VKiH6IaXozXeV2u79hfCcoQBRlpnTMIohK9VVanK59S+bqBsYRKzxKIc5At0HLLJOuyvfm66FiEgSXNrqeiy0/JB80GapIY15RUtlgCWhNDiwuRLkN5mXzBWjNMKpH5wM96jslTBpHtlcvUl1iBOV0Ye/xMb4FtWh1SBbxKJfFGSlxclNVa9+Za1s0PmU0SMU/eIxf/H0dL7eHUwR0xquTnei8wvm6F5boTYw/0gzN2Oy3VrnHtx12QP+xefmx/oc4tX4KDoqP5/2v/ee5Cnb/zYSyBu7v3jqJ1G8LQYAP23kPXwfTNUrV3QzIGiZPnP/q/ESEO0+g7PovubUxfNzXmxh2AXeXxY8/Q==
  template:
    metadata:
      name: backend-secret
      namespace: backend-team
    type: Opaque
