---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-secret
  namespace: backend-team
spec:
  encryptedData:
    DATABASE_URL: AgAWqpPqbT/DaTIradiAndyN4lNyne13GLirLqG4FF/qFDkYPbm4YfvIwA4pI8sOMJQYV7c9RT7dg+TAiR4bzII1l8laYVVdP+q2OdvQLibEPiL8vdq98YTmkeMAvdt52oaBZEBUuPNIvdUIKRr7mhtZeHRtH3yq0D9aQBlgwF852ka16XvwggSm5iqMe1uwNzthNV+J2hFe8X+bV8+YKXsipPTsnrMy8L1wp3blMkYnl1AWpCoToMgBfwf8VscL6p0G2EW+iEN5I9vMAA++slssgjMhzASJ3Y0NX6xmiQQGumNCEmlvgnM4tF0Ga+VRTF9Ebd9Gsy5tiLpx3Ab0tBMocv8TeIMdZNN6da8PnEouuXK97IvA7TzoxdzhLtmoAe7pU7CTxWh8gCkaYAWYfWY74Pohx4X8030bCYirPuE0AFcpU2ETSn+jDs3RYEw9SY2/3yr0Ngx4H/CAjUZDvSeoIzztHwBVt3LEGCbckcETuNWBrvA63zNnK1TJFtwtgzyLCLWMRG98wZpQNVoXE5dHxRs9mVKPaJkXHGDqtBWcZAa9eXj9PoT4zrZcOyWFAkEFHHwXghT8yPfRhaeK1SZmjfr1k9KQ3yk01HZrYGsY4bPs7vIiverQYd/kb8jSwxNfbrRLOcmiqT5kU4XnmG48qgAeUuIRqiTfpJ2ylSufP5vULLvuNhQTudYmCRoHEMWPqi1pUAx2nPMnnOZQKZGsl+m1nvEC6Wxie87bypgIfTJlRiysRl8l09ctuodQn3zuN3O+xWG2e0EHzoGpN9ANSaMn9IVXFiJK
  template:
    metadata:
      name: backend-secret
      namespace: backend-team
    type: Opaque
