apiVersion: v1
kind: Namespace
metadata:
  name: backend-team
  labels:
    name: backend-team
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: backend-team
  labels:
    app: kub
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kub
  template:
    metadata:
      labels:
        app: kub
    spec:
      containers:
        - name: kub-1
          image: shyamagarwaldev/kub-1:5
          env:
            - name: DATABASE_URL
              value: postgresql://postgres:postgres@db-service-clusterip.db-team.svc.cluster.local:5432/postgres
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: kub
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30007
  type: NodePort
