apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Release.Name }}-backend-deployment
    namespace: {{ .Values.backend.namespace }}
spec:
    replicas: {{ .Values.backend.replicas }}
    selector:
        matchLabels:
            app: backend
    template:
        metadata:
            labels:
                app: backend
        spec:
            containers:
                - name: backend
                  image: {{ .Values.backend.image.repository }}:{{.Values.backend.image.tag }}
                  ports:
                    - containerPort: {{ .Values.backend.port }}
                  env:
                    - name: DATABASE_URL
                      valueFrom:
                        secretKeyRef:
                            name: {{ .Values.backend.secretName }}
                            key: DATABASE_URL


